<#

.SYNOPSIS

Cleans up temporary files generated by the CalculiX preprocesor and solver.

.DESCRIPTION

This wil delete the following files;

*.nam   named sets
*.equ   equations
*.sur   surface sets
*.msh   meshes
*.log   log files
*.12d   convergance files
*.sta   convergance files
*.cgv   convergance files
*.con   tie constraints

Note that this will not delete the result files “job.frd” and “job.dat”.

#>
Remove-Item -Path "*.nam" -ErrorAction SilentlyContinue
Remove-Item -Path "*.equ" -ErrorAction SilentlyContinue
Remove-Item -Path "*.sur" -ErrorAction SilentlyContinue
Remove-Item -Path "*.msh" -ErrorAction SilentlyContinue
Remove-Item -Path "*.log" -ErrorAction SilentlyContinue
Remove-Item -Path "*.12d" -ErrorAction SilentlyContinue
Remove-Item -Path "*.sta" -ErrorAction SilentlyContinue
Remove-Item -Path "*.cvg" -ErrorAction SilentlyContinue
Remove-Item -Path "*.con" -ErrorAction SilentlyContinue
Remove-Item -Path "spooles.out" -ErrorAction SilentlyContinue
